CLUSTAL multiple sequence alignment by MUSCLE (3.8)


CuAOzeta          ATGG--CCTCAGCTTCGAAAAAGACGTCGGCATGTCCTCACCACGGTGGCTCTCTTCCG-
CuAObeta          ATGA--ACACATCAA-------------------TACTTGCCA---TACTTTTTCTCAT-
CuAOalpha3        ATGG--CTCCACTTC-------------------ACTTCACCATTCTCATCCTTTTCTC-
CuAOalpha1        ATGGTGAACCGTGAT-------------------AATTCTATTGTGGCTTTATCCTTTTT
CuAOalpha2        ATGG--CTCAAGTTC-------------------ACTTAACCA---TTTTTATATTTTC-
CuAOgamma2        ATGG--TGGAACTTT-------------------CGTTCTCTCAGCTCCTTGTCTTACT-
CuAOgamma1        ATGG--CAGAACCAT-------------------CTTTTGCTCGTCTGTTTCTCTTGTT-
CuAOepsilon1      ATGG--AGCCAAAAC-------------------TCTCCTCTCGTTTGTTTCTTCTCATC
CuAOdelta         ATGG--ACCAAAAAA-------------------GCTTTTTCCGGTTGATTTTTCTCATA
CuAOepsilon2      ATGG--AAACACCGT-------------------T-------------------------
                  ***                                                         

CuAOzeta          ---------CCTCCCAAACTCGTCTCCGCTGCTCCCGATACCGTTG--CTGTATGGTCCG
CuAObeta          ----------------ACAATGTGTTTTCACTCTTGGTCTCCATTT--------------
CuAOalpha3        -----------TTTCGTTATCGTAGTCTCATCCTCAAGCTTTACTC--------------
CuAOalpha1        TATGCTCTTCTTGCTTGTGTTACATCTGCATTTTGAAACTACAACA--GCTGCGCGAAAA
CuAOalpha2        -----------TTCCATTTTCGTAATCTCATCATCTAGCTTCATCC--------------
CuAOgamma2        -----------TTTAAGCTTACTCTTTCTCTTCACTACTCTCGCGT--------------
CuAOgamma1        -----------CTTCAGCTTTCTCCTTATCTTTGCCACCTACTCTT--------------
CuAOepsilon1      ACCACGGCTTGTTTCATCCTCTTATTCACTTCCACTAACTTCTCTCAAGCGCCATCATCC
CuAOdelta         GTCACAGCTGGTTTCATCATCTCCTTCACTTCCACTAACTTCCCTCACGCGC--------
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          ACGCTGACGATCAGCGAGCCTCTAAAGTTTCTTTGGAATCCGTTATCCGCCCTGTCGATT
CuAObeta          ------------------------------------------------------------
CuAOalpha3        ------------------------------------------------------------
CuAOalpha1        CCAGTTAGAGTGTTTGGTCCGCCAAGTTCTATCGAGTGGTCACCACCATCACCACCAAAG
CuAOalpha2        ------------------------------------------------------------
CuAOgamma2        ------------------------------------------------------------
CuAOgamma1        ------GGGTCTTTGGACCCGACTCAGGCT---------------TCTTGTTCGG-TACT
CuAOepsilon1      ACGGCGAAGCTTTTCGACTGCACAAAATCT---------------TCGTCTTCACCTTTT
CuAOdelta         -CGACGAGGCTTCTTGATTGCACCGACTCT---------------TCTTCTTCACCTCTT
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          CGTTTCCTGATAATACTGCCAAGAAACCTGCC-----------AACAAAGGGATTTCTGT
CuAObeta          ------------------------------------------------------------
CuAOalpha3        ------------------------------------------------------------
CuAOalpha1        GATGACTTTGAATGGTTCGAGATCAATATATACAAGAACATTGAACAAACTGCATTCCGA
CuAOalpha2        ------------------------------------------------------------
CuAOgamma2        CAAGTTCCAAGACCCCCCGATTCAAGTA---------------TTCG-------------
CuAOgamma1        CGTGTCCGGAAAACTCTCGGCTCGAATC---------------GTCA-------------
CuAOepsilon1      TGTGCGTCAAGAAACTTCCTCTTTAACA------------------AAAACACTCGGCCC
CuAOdelta         TGCGCTTCGAGAAACTTTCTTTTCAACA---------------AACAACAACCACGACCT
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          GATGCCAAGGACTG----------------------------------------------
CuAObeta          ------------------------------------------------------------
CuAOalpha3        ------------------------------------------------------------
CuAOalpha1        CCCACTGGTCAAGGTCCTAGCCAAGGCATCGGACACAAGGATCCACCTGTATTTTCTTCC
CuAOalpha2        ------------------------------------------------------------
CuAOgamma2        ------------------------------------------------------------
CuAOgamma1        -----------------------------AGTCCACGTTGACCACTCT------------
CuAOepsilon1      ATTTCTAAAAACATTCCCAAAACAAAACCCAAAAACCATGACCACGTT------------
CuAOdelta         ATTCCTAAACATGATCCTAAACCAAATACCAAAAACCATGATCACGTG------------
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          -------------------------------AAACCAAGCACCCATTGGATCCTCTTTCT
CuAObeta          --------------------------------------CCACCCACTTGATCCCTTAACT
CuAOalpha3        -------------------------------CACCGCGTCACCCATTTGATCCCTTAACC
CuAOalpha1        GTTTTTGTAATCGGATCCTTAAGCTTCATCCCACCGCCTCACCCATTTGATCCCTTGACT
CuAOalpha2        -------------------------------CACCTCCTCACCCCTTCGATCCCTTGACC
CuAOgamma2        ------------------------TTAGAGAAGCCTCACCACCCACTTGACCCACTAACG
CuAOgamma1        ------------------------TTAGAAAAGCCTCATCATCCACTTGATCCACTAACG
CuAOepsilon1      ------------------------TCCGATACACCGAACCACCCTCTTGACCCACTTACC
CuAOdelta         ------------------------TCCGATACACCAAACCATCCTCTAGACCCACTCACG
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          GCTGCAGAAATATCAGTTGCTGTGGCGACTGTTCGCGCAGCTGGTGCCAATCCTGAGGTT
CuAObeta          CCCCAAGAAAT-CAACAAAACAAGCTTTATCGTC-------AAGAAATCTCATCTAGGCA
CuAOalpha3        GAGACCGAACT-CAAACTCGTCCGAACCATCATC----AACAAGTCGTACCCCGTTGGTC
CuAOalpha1        GAGATCGAACT-CAATCTCGTCCGTAACATCATC----AACGAAAGGTACCCCATTGGTC
CuAOalpha2        GAGACTGAACT-CAAACTTGTCCGTAACATCATC----AACAAGTCGTACCCTATTGGTC
CuAOgamma2        ACACCTGAAAT-AAAGAGAGTCCAAACCATCCTCTCGGGTCATGATCCGGGTTTCGGGTC
CuAOgamma1        GTGCGAGAAAT-CAATAGAGTCAGAACAATACTCTCGAACCATGACCCGGGTTTTGGTTC
CuAOepsilon1      GTCATGGAGAT-CAACAAAGTCCGATCAATCCTCTCCTCCCACG---CGCTCTTCGCCTC
CuAOdelta         GTGTCGGAGAT-TAACAAAATCCGATCAATACTCTCTTCTCACG---CGCTATTCACTTC
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          AGGGATG---GCATGCGTTTCATTGAGGTGGCATCAGTGGAACCAGATAAACAAGTTGTG
CuAObeta          ACCTCAAAGATCTCACATTTCATTATCTCGACCTCGAA-GAACCAAACAAGAGCCACGT-
CuAOalpha3        CGAATCATAAGTTCACTTTCCAATACGTTGGTCTCAAC-GAACCCAACAAGTCTCTAGT-
CuAOalpha1        TGGAACATAGGTTCACTTTCCAGTACGTGGGTCTCAAC-GAACCCGACAAGTCCCTAGT-
CuAOalpha2        ATAACCATAAGTTCACGTTCCAATATGTGGGTCTCAAC-GAGCCTGAAAAGTCCCTAGT-
CuAOgamma2        CGGGTCA----ACCATCATTCACGCCATGGCTCTCGAC-GAGCCGGATAAGCAACGTGT-
CuAOgamma1        CGGGTCG----GCCACGATTCACTCCATGGCTCTCGAT-GAGCCGGAGAAGTCACGTGT-
CuAOepsilon1      ACGTGTA-CCCCACTTGCTTAACTCCGTCGTTCTTGAA-GAGCCAGACAAGAATCTAGT-
CuAOdelta         CGGTACA-CCACACGCGCTCCACACCGTCGTTCTTGAA-GAGCCTGAGAAGAATCTTGT-
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          GCGCTCGCTGATGCTTACTTTTTCCCACCGTTCCAGCCATCACTACTTCCAAGAACTAAA
CuAObeta          ------------------------------------CCTCCAATGG---CTATCACCAAA
CuAOalpha3        ------------------------------------CTTGTCTTGGTACTCATCACCGAA
CuAOalpha1        ------------------------------------CTTATCCTGGGTTTCATCACAATA
CuAOalpha2        ------------------------------------CTTGTCGTGGCACTCATCACCAGA
CuAOgamma2        ------------------------------------CATCCGGTGG------------AA
CuAOgamma1        ------------------------------------CGTCCAGTGG------------AA
CuAOepsilon1      ------------------------------------CAGACAATGG------------GA
CuAOdelta         ------------------------------------CCGTCACTGG------------GA
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          TCTGGACCTGTGATTCCGATGAAGCTCCCTCCA------AGGCGAGCTAGACTTGTTGTT
CuAObeta          TCCCTCC-----------AAGAAACCACCACCCCCACGTCGTCGCTCATTCGTCGTGGTT
CuAOalpha3        TCATACC-----------ATCAAACCACCACCA------CGCCAAGCGTTCGTCATTGCT
CuAOalpha1        CCACAAT-----------GTCAAGTCACCACCA------CGTCAGGCATTCGTCATCGCT
CuAOalpha2        CCGCAAC-----------GTCAAACCACCACCA------CGTCAAGCTTTTGTCATCGCC
CuAOgamma2        GAAAGGT-----------GATCGTCTCCCGCCG------CGAAGAGCGGAGATTCTTGCT
CuAOgamma1        GAAGGGA-----------AATAAGCTTCTGTCA------CGAAGAGCTGCGGTCGTAGCT
CuAOepsilon1      GAAAGGA-----------GACCAACTACCACCA------AGAAAGGCCTCAGTGATCGCA
CuAOdelta         AAAAGGG-----------AACCCACTTCCTCCG------AGGAAAGCTTCCGTCATCGCA
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          TA---CAACCAAAAGTCTAATGAGACAAGTGTATGGATTGTGGCATTGTCTGAAGTTCAT
CuAObeta          CGAGCCGGTGGTCAAACCTACGAG------------------------------------
CuAOalpha3        CGAGACAACGGAAAGACCAGAGAG------------------------------------
CuAOalpha1        CGAGATCACGGAAAGACCCGAGAG------------------------------------
CuAOalpha2        CGAGATAAGGGCATGAGCCGAGAG------------------------------------
CuAOgamma2        ATGTCTAACGGCGAGAGTCACGTG------------------------------------
CuAOgamma1        TATTGGGGTGGTCAAACACATGAG------------------------------------
CuAOepsilon1      CGTGTTGGCGGCAACTCGCACTTG------------------------------------
CuAOdelta         CGTGTTGGCGCGGACACGCACGTG------------------------------------
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          GCTGTCACTCGGGGTGGACATCACAGGGGAAGAGTTGTTTCCTCACAAGTTATACCTGAT
CuAObeta          -------CTCATCATCGACCTAACCACGAGCAAGATTGCATCCTCCCGCATCTACACAGG
CuAOalpha3        -------ATAGTCCTTGACTTTTCCTCTCGTGCCATCGTCTCGGACAAAATTCACGTAGG
CuAOalpha1        -------ATCGTCGTGGACTTTGCCTCTCAAGCCATTGTTTCGGAAAAGATTCACGTAGG
CuAOalpha2        -------ATCGTTATTGACTTTTCCACTCGAGCAATTGTCTCGAACAAGATCCATGTAGG
CuAOgamma2        -------CTCACGGTGGATCTTAAATCCGGTCGGGTTGTTTCTGATTTGGTCAACCCGAC
CuAOgamma1        -------ATAACGGTGGATCTTGATTCGGGTCGGGTAGTTTCTGATGTGATTAACCGGAC
CuAOepsilon1      -------CTCATCGTTGACTTATCTACAAGTCGTGTTGATC---AAGCGGATAGTCCGGT
CuAOdelta         -------CTCACCGTTGATATCTCTACGGGTCGGGTAGATTCAGA---GAATAGCCCGGT
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          G------TTCAGCCACCCATGGATGCGGCTGAATATGCTGAATGTGA----AGCGATTGT
CuAObeta          C------CATGGTTTCCCCTCATTCACATTCATAGAGCTTTTCAAAGCAAGCAAGCTTCC
CuAOalpha3        A------AATGGTTACCCTATGCTCTCAAACGACGAGCAAGAAGCATCCACCGAGCTTGT
CuAOalpha1        A------AATGGTTACCCTATGCTTACAATTGACGAGCAACAAGCAACCAGCGAGCTTGT
CuAOalpha2        C------AATGGTAACCCAATGCTAACTATTGACGAGCAGCAAGCAGCCACCGCGGTTGT
CuAOgamma2        T------TTTGGATACCCGATTCTTACTATGAAGGATATCATCGCAGTCTCACAGGTTCC
CuAOgamma1        T------TCAGGGTATCCGATTCTCACCTTGAACGACGTCTTCGCTGCTTCGCAGGTTCC
CuAOepsilon1      TCCTGAATCCGGTTACCCGATTGTGACGTCGGAGGAGATGGACAGTGCCGCGTCTGCACC
CuAOdelta         TCGTGTTTCTGGTTACCCGATGATGACTATAGAAGAGATGAACGATATCACTGTTGTACC
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          CAAAGACTTCCCACCATTCATAGAGGCAATGAAGAGGAGAGGTATTGAAGACATGGATCT
CuAObeta          TCTAACTTACCCACCTTTCAAGAAATCGATTCTCGATCGATCCCTAAACATCTCCGAG--
CuAOalpha3        TGTCAAGTTCAAGCCGTTTATTGACTCGGTCGCGAAACGTGGCTTAAACGTTTCGGAG--
CuAOalpha1        TCTCAAGTTCAAGCCGTTCCGTGACTCAATCAGGAGACGTGGCTTGAACGTGTCCGAG--
CuAOalpha2        TCAAAAGTACAAGCCGTTCTGTGACTCGATAATAAAACGCGGCTTGAACTTGTCGGAA--
CuAOgamma2        TTACAAGAGCGTGGAGTTCAATCGCTCAATCGAAGCGCGTGGGATTCCGTTCTCCGGT--
CuAOgamma1        TTTGAAGAGCTTGGAATTTAACCGCTCCATTGAAGCTCGTGGGGTTAAGTTTTCCGAT--
CuAOepsilon1      GTTCTCAAACGCAGATTTCAACCGTACGATCAACTCTCGTGGAGTTAATCTAACGGAC--
CuAOdelta         ATTTTCAAACGCGGATTTCAACCGTACGATCATCTCTCGTGGAGTTAATCTAACGGAC--
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          AGTGATGGTTGATCCCTGGTGTGTGGGTTATCACAGTGAGGCTGACGCTCCTAGTCGTAG
CuAObeta          -GTTTCTTGCATCCCTTTCACCGTTGGTTGGTACGGAGAAACCA------CCACGAGACG
CuAOalpha3        -ATCGTGTTCACGACGTCAACGATTGGATGGTACGGTGAGACTAAGGCCGAGGCGGAGCG
CuAOalpha1        -GTTGTTGTCACGACCTCAACGATGGGATGGTTTGGTGAGGCGA------AGCCGGAGAG
CuAOalpha2        -GTTGTGGTCACCTCCTCAACGATGGGATGGTTTGGTGAGACAA------AGACGAAGAG
CuAOgamma2        -TTGATTTGTATTACACCGTTCGCCGGTTGGTATGGACCGGACGAAG---AAGGACGACG
CuAOgamma1        -TTAGCTTGCATCACACCGTTTGCCGGATGGTTTGGATCGGAGGAAG---AAGGACGTAG
CuAOepsilon1      -GTGATTTGTATCCCAATCTCTAGTGGCTGGTTTGGTAATAAAGACGACAACACCAAAAG
CuAOdelta         -GTGATTTGTTTCCCAATCTCTTGTGGTTGGTTTGGTAATAAAGAAGAAAACGC---GAG
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          GCTTGCAAAGCCCC-----TTATATACTGTCGGACTGATAGTGATTCCCCTATGGAAAAT
CuAObeta          TGAACTCAAAGCCTCTTGCTTTTACAGAGACGGATCAGT-----------------CAAC
CuAOalpha3        AGTTATTAGATTGATGCCGTTTTATCTTGACGGCACCGT-----------------TAAT
CuAOalpha1        GCTTATAAAAAAGAGACCGTTTTATCTGAATGGGTCGGT-----------------GAAC
CuAOalpha2        GTTTATAAGAACGATACCCTTTTATCTAAACGGATCGGT-----------------GAAC
CuAOgamma2        AGTCATAAAGATCCAATGTTTCTCAAAGCAAGACACTGT-----------------CAAT
CuAOgamma1        AGTCATAAGAGTTCAATGTTTCACGTTACAAGGCACTAC-----------------CAAT
CuAOepsilon1      GGTTACTAAAATTCAGTGTTTCTCAACTCAAGATACCCC-----------------TAAT
CuAOdelta         GGTAATTAAAAGTCAGTGTTTCATGACACAAGGAACACC-----------------TAAC
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          GGATATGCTCGTCCAGTTGAGGGCATTTATGTACTTGTAGACATGCAAAACATGGTGGTG
CuAObeta          GTCTTCACAAGACCCATCGAAGGAATCACCGTAACTATAGACGTCGACTCAATGCAAGTC
CuAOalpha3        ATGTATCTTAGACCTATTGAAGGAATGACGATAATCGTTAATCTTGATGAGATGAAGGTA
CuAOalpha1        ACTTACCTTAGACCTATAGAAGGAATGACGATAATCGTTAACCTTGACCAGATGAAAGTA
CuAOalpha2        ACGTATCTTAGACCAATTGAAGGAATGACGATAATCGTTAACCTTGACCAGATGAAAGTA
CuAOgamma2        TTCTACATGAGACCTATCGAAGGACTTTATTTAACCGTCGATATGGATAAATTAGAGATC
CuAOgamma1        TATTTTATGAGACCACTCGAAGGACTTTATGTAACGGTCGATCTAGACAAATTGGAGGTT
CuAOepsilon1      TTCTACATGCGACCTATCGAAGGTTTGACTCTGCTTTTTGATTTAGACACGAAGCGAATA
CuAOdelta         TTCTACATGCGTCCTATCGAAGGTTTAACCATTCTCATCGATTTAGATACAAAGCAAGTG
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          ATTGAATTTGAAGACCGTAAGTTTGTGCCACTCCCCCCACCTGACCCTTTGAGGA---AT
CuAObeta          ATCAAGTACTCCGACA---GATTC---CGAAAGCCTATCCCTGATAAAGAAGGTAACGAC
CuAOalpha3        TCGGAGTTTAAGGACA---GGTCA---GTGGTTACTATGCCCATAGCTAACGGAACGGAG
CuAOalpha1        ACGAAGTTTAGAGATA---GGTTT---ACGAGTCCTTTGCCTAATGCTAAGGGAACCGAG
CuAOalpha2        ACGGGGTTCAAGGACA---GGTTC---ACGGGTCCTATGCCGAAGGCTAACGGGAGAGAG
CuAOgamma2        ATCAAGATTGTAGACA---ATGGA---CCGGTTCCGGTTCCCAAGTCTACCGGTACGGAA
CuAOgamma1        ATCAAGATCATCGATA---AAGGC---CCAATTCCAATTCCCAAAGCCTCCGGTACAGAA
CuAOepsilon1      CTTGAGATAACAGATACCGGTCAA---TCAATACCCATACCCGGTTCAACTAATACCGAT
CuAOdelta         ATCGAGATAACCGATACAGGTCGG---GCTATACCCATACCCGGTTCAACCAATACCGAT
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          TATACCCCAGGTGAAAGTAGAGGGGGTGTTGATAGAAGTGATGTTAAGCCTCTCCAGATT
CuAObeta          TTTAGGAC--------------------TAAACACAGACCCT-----TCCCGTTCTTTTG
CuAOalpha3        TACCGTATCTCGAAGCTTAACCCACCCTTTGGACCGACGCTTCATAACGCCGTCCTTTTG
CuAOalpha1        TTCCGTATCTCGAAGCTAAAACCGCCGTTTGGCCCGTCGCTTCAAAACGCCGTCCTTTTT
CuAOalpha2        TACCGTATCTCAAAGCTCAAGCCGCCGTTTGGCCCGTCGCTTCGAAGTGCCGTCGTTTTC
CuAOgamma2        TATAGATATGGGTTTCTTAATGAAACGGTATATATGGACCGTGTCAACCCAATGTCGATG
CuAOgamma1        TACCGGTTTGGTGTTCAGAATAAACCGGTGCATATGGATCGTATTAACCCGATTTCGATG
CuAOepsilon1      TATCGATATTCTACTCTTCCAAACCATGACAAAACCAGACCCCTCAATACAATATCACTC
CuAOdelta         TACCGCTTCCAAAAGCTCGCAACCACCGACAAAACTCGGCCTCTAAACCCGATATCCATT
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          ATTCAGCCTGAAGGTCCAAGTTTTCGTGTA---AGGGGTTACTTTGTCGAGTGGCAGAAG
CuAObeta          CAACGTCTC--CGACACAGGCTTCAAGATA---CTCGGCAATAGAGTCAAGTGGGCTAAC
CuAOalpha3        ---CAGCCGGATGGTCCGGGCTTCAAGGTC---GATGGACACATCGTGAGGTGGGCAAAT
CuAOalpha1        ---CAGTCGGAGGGGCCTGGGTTTAAAATC---GATGGACACACGAATAGATGGGCAAAT
CuAOalpha2        ---CAGCCGGACGGTCCAGGGTTTAAGATC---GATGGACACGTCGTGAGATGGGCAAAT
CuAOgamma2        GAGCAACCGGACGGTCCAAGTTTTCAAGTTGAGGATGGATACTTGGTTAAGTGGGCGAAT
CuAOgamma1        GAGCAACCTGACGGTCCCAGTTTTAGGGTCGAAGATGGGCATTTGGTTAAGTGGGCTAAT
CuAOepsilon1      GAGCAGCCACGTGGACCAAGCTTCGTTATCGAAGATAACCATTTAGTAAAATGGGCAAAT
CuAOdelta         GAGCAGCCACGTGGTCCAAGCTTCGTGATAGAGGACAACCATCTAGTGAAATGGGCAAAT
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          TGGAACTTTCGTATTGGATTCACTCCAAGGGAAGGTTTAGTCATACATTCGGTAGCATAT
CuAObeta          TGGAAATTCCACGTCGGATTTACCGCAAGAGCGGGAGTAACTATATCGACGGCTTCGGTT
CuAOalpha3        TGGGAATTTCACATATCGTTCGATGTTCGAGCTGGCATCGTCATATCTCTCGCATCCCTT
CuAOalpha1        TGGGAATTCCACATGTCATTTGACGTACGAGCTGGTCTTGTTATCTCTCTTGCGTCCATT
CuAOalpha2        TGGGAGTTTCACATGTCATTTGACGTTCGAGCCGGTCTTGTCATCTCTCTCGCGTCCATT
CuAOgamma2        TGGAAATTTCATATTAAACCGGATCAACGTGCCGGTATGATTATCTCACAGGCTACAGTT
CuAOgamma1        TGGGTTTTCCATGTTAAAGCTGACCAACGAGCCGGTATGATCATATCTCAGGCCACGGTT
CuAOepsilon1      TGGGAATTTCATTTAAAACCAGACCCGAGAGCCGGTCTGATTATGTCCCAGGTCAAAATA
CuAOdelta         TGGGAATTTCATCTAAAACCTGACCCGAGAGCAGGTGTGGTAATATCACGGGTAAGAGTA
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          GTTGAT-----GGCAGTCGAGGTCGAAGGCCTGTTGCACACAGGCTAAGTTTTGTGGAAA
CuAObeta          CTTGACCCGAGAACCAAAAGGTTTCGACGAGTGATGTATAGAGGGCACGTGT--CAGAGA
CuAOalpha3        TTCGACACGGACGTGAACAAATACCGGCAAGTCCTATATAAAGGTCACTTAT--CGGAAA
CuAOalpha1        TTCGACATGGACGTTAACAAATACCGTCAAGTCCTATACAAAGGCCATTTGT--CGGAAA
CuAOalpha2        TTCGACATGGACATGAACAGATACCGGCAAGTCCTATACAAAGGTCATTTGT--CGGAGA
CuAOgamma2        CGTGATTCCAAGACAGGTGAAGCAAGAAGTGTAATGTACAAAGGTTTTGCGT--CGGAGT
CuAOgamma1        CGTGACTCCGAGACAGGTGAACCAAGAAGTGTGATGTACAAAGGATTCCCAT--CAGAGT
CuAOepsilon1      CACGACCCGGATACACAAGAAACACGTGAAGTGATGTACAAAGGTTTCGTGT--CGGAGC
CuAOdelta         CACGACCCGGATACTCATGAGACACGTGACGTGATGTACAAAGGTTTCGTGT--CTGAAC
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          TGGTTGTGCCTTATGGCGATCCTAATGAGCCACATTACAGGAAAAATGCTTTTGATGCAG
CuAObeta          CTTTTGTTCCGTACATGGACCCAACCTACGAATGGTACTACCGTACGTTCATGGACATTG
CuAOalpha3        TGTTCATACCTTACATGGACCCAAGTGATGATTGGTATTTCATTACTTATCTTGATTGTG
CuAOalpha1        TATTTGTACCTTATATGGATCCAAGTGAAGATTGGTACTTCAGAACTTTTTTTGACTGTG
CuAOalpha2        TGTTCGTACCTTACATGGACCCAAATGACGACTGGTACTTCATTAGTTACCTAGACTGTG
CuAOgamma2        TGTTCGTACCGAATATGGATCCAGGGGAAGGTTGGTATTCAAAAGCTTACATGGATGCTG
CuAOgamma1        TGTTTGTACCGTACATGGACCCTGAGGAAGGATGGTACTACAAAGGTTATATGGATGCAG
CuAOepsilon1      TTTTTGTTCCGTACATGGATCCATCGGAAGCTTGGTACTTTAAGACTTACATGGACGCAG
CuAOdelta         TTTTTGTTCCGTACATGGATCCATCGGACGCGTGGTACTTTAAGACTTACATGGACGCAG
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          GGGAGGATGGTCTCGGGAAAAACGCACATTCGCTTAA-----------------------
CuAObeta          GAGAGTTTGGTTTCGGGAGATCCGCCGTGAATCTGCA-----------------------
CuAOalpha3        GCGATTTTGGCTGCGGTCAATGCGCCGTATCTCTTCA-----------------------
CuAOalpha1        GTGAATTTGGTTGCGGCCAATATGCTGTGTCTCTTGA-----------------------
CuAOalpha2        GTGAATTTGGCTGCGGCCAAACTGCCGTATCCCTTGA-----------------------
CuAOgamma2        GAGAGTTTGGTTTAGGACCTTCTTCAATGCCACTTGT-----------------------
CuAOgamma1        GCGAGCTCGGTTTAGGACCCACGGCAATGCCGCTCGT-----------------------
CuAOepsilon1      GAGAGTACGGGTTCGGGTTACAAGCCATGCCGCTGGAGCCAGTGGCGGAGCCAAAAAACT
CuAOdelta         GGGAATACGGGTTCGGGTTACAAGCCATGCCACTCGT-----------------------
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          ----------GAAGGGGTGTGACTGTCTGGGATCTATCAAGTACTTCGATGCCCATTTCA
CuAObeta          ----------GCCACTCATTGACTGCCCGCAAAACGCTGCGTTTTTAGATGGGCACGTGG
CuAOalpha3        ----------ACCGTACACTGATTGTCCAGCGGGTGCAGTTTTTATGGATGGTATTTTTG
CuAOalpha1        ----------ACCTTACACCGATTGTCCCGGTAACGCTGCCTTCATGGACGGCGTCTTTG
CuAOalpha2        ----------GCCGTATACTGATTGTCCCCCGAATGCCGCTTTCATGGATGGCATCTTCC
CuAOgamma2        ----------GCCACTCAACGACTGTCCTCGAAACGCTTACTACATTGATGGTTTCTTCG
CuAOgamma1        ----------GCCTCTCAACGATTGCCCTCGAAATTCTTACTATATAGACGGTGTTTTCG
CuAOepsilon1      TATTCATCGGGCCGCTTAATGATTGTCCAAGAAACGCCGTTTATATGGACGGAACATTCG
CuAOdelta         ----------ACCGCTTAATGATTGTCCACGAAACGCAGCCTATATGGACGGAGTTTTCG
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          CAAATTTCACTGGAGGAGTTGAAACAATTGAGAACTGTGTTTGCTTGCATGAAGAAGATC
CuAObeta          CCGGACCAGATGGGACAGCTCAGAAGATGACCAATGTGATGTGTGTATTCGAGAAAAACG
CuAOalpha3        CTGGTCAAGATGGAACTCCCGCAAAAATCCCAAAAGTTATGTGCATTTTTGAAAAATATG
CuAOalpha1        CAAGCCAAGACGGAACTCCGATAAAAATCACAAATGTTATGTGCATCTTCGAGAAATATG
CuAOalpha2        CGGGACAAGATGGAACTCCTACAAAAATATCGAATGTTATGTGCATTTTCGAAAAATATG
CuAOgamma2        CTTCTCCTGAAGGCATTCCAATACTTCAACCTAACATGATCTGCTTGTTCGAACGCTACG
CuAOgamma1        CCTCTCCAGACGGCAAACCCATTGTTCAACCTAATATGATATGCTTGTTTGAACGCTATG
CuAOepsilon1      CGGCGGCTGACGGAACGCCATATGTGAGAGAGAATATGATTTGTGTGTTTGAGAGTTATG
CuAOdelta         CCGCAGCCGATGGAACACCGTTCGTGAGAGAAAACATGGTTTGTATCTTTGAGAGTTACG
CuAOepsilon2      ------------------------------------------------------------
                                                                              

CuAOzeta          ATGGG---ATTTTGTGGAAACATCAGGA---------CTGGAGAACAGGATTAGCCGAAG
CuAObeta          GTTACGGTGCTTCTTTTAGACACACCGAGATTAATGTTCCAGGACAAGTGATAACAAGTG
CuAOalpha3        CTGGAGATATCATGTGGCGACATACAGAAGCTGAAATTCCAAACTTAGAAATTACGGAGG
CuAOalpha1        CCGGAGACATTATGTGGCGGCATACCGAAATTGAAATTCCCGGCTTA---------AAAG
CuAOalpha2        CTGGAGACATTATGTGGCGACATACCGAAGCTGAAGTACCCGGCTTAAAAATCACAGAGG
CuAOgamma2        CGGGTGACACTAGCTGGCGACACTCTGAGATTCTTCTCCCTGGTGTAGATATAAGAGAGT
CuAOgamma1        CAGGCGATATCAGCTGGCGACATTCTGAGATCCTTTTTGCCAATGCCGATATAAGAGAGT
CuAOepsilon1      CCGGAGATATTGCGTGGCGTCACACCGAG-------------------------------
CuAOdelta         CCGGAGATATTGGGTGGCGTCACTCCGAAAGCCCCATCACCGGTATACCGATAAGGGAAG
CuAOepsilon2      ----------------------------------------------------AAGGGAAG
                                                                              

CuAOzeta          TGCGAAGATCTAGGAGACTAACTGTCTCTTTTCTATGTACTGTTGCCAACTACGAGTATG
CuAObeta          GGGAAGCTGAAATAAGTTTAGTGGTTAGAATGGTGGCCACACTTGGAAACTATGATTACA
CuAOalpha3        TTAGACCGGACGTAAGTCTTGTAGCCCGGATTGTGACGACCGTGGGAAACTATGACTACA
CuAOalpha1        TAAGACCGGACGTAAGTCTTGTGGTCCGGATGGTGACGACCGTGGGGAACTACGACTATA
CuAOalpha2        TTAGACCAGATGTAAGTCTTGTAGCCCGGATGGTGACGACAGTGGGGAACTACGACTACA
CuAOgamma2        CAAGGGCAAAGGTTACACTGGTAGCTAGAATGGCATGTTCTGTTGGGAACTATGATTATA
CuAOgamma1        CAAGGCCAAAAGTTACATTGGTAGCTCGAATGGCAACTTCGGTTGGAAATTACGACTATA
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         TGAGACCAAAAGTGACGCTAGTGGTACGAATGGCAGCTTCGGTAGGTAACTATGATTACA
CuAOepsilon2      TGAGACCAAAGGTGACACTTGTGGTACGAATGGTAGCTTCAGTGGGTAACTACGATTACA
                                                                              

CuAOzeta          GGTTTTACTGGCACTTCTACCAGGATGGGAAAATCGAAGCTGAAGTAAAACTTACTGGTA
CuAObeta          TAGTGGATTGGGAATTTAAAAAGAATGGAGCCATCAGAGTTGGGGTGGATTTGACTGGAG
CuAOalpha3        TAGTTGATTATGAGTTCAAGCCTAGTGGTTCCATCAAAATGGGGGTCGGCTTAACCGGTG
CuAOalpha1        TAGTTGATTACGAGTTCAAACCTAGTGGTTCCATCAAAATTGGGGTCGGTTTAACAGGTG
CuAOalpha2        TCATCGAGTATGAGTTCAAACCAAGTGGTTCCATCAAAATGGGGGTCGGTTTAACCGGTG
CuAOgamma2        TTTTTGATTGGGAGTTTCAAATGGATGGTGTGATTCGTGTTACGGTCGCGGCCTCGGGGA
CuAOgamma1        TTTTCGATTGGGAGTTTCAGACTGATGGTTTGATCCGTGTTACGGTCGCGGCTTCGGGAA
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         TCATTGATTACGAGTTCCAAACTGATGGGCTTATAAAAGCTAAGGTCGGGCTAAGTGGAA
CuAOepsilon2      TCATTGATTATGAGTTCCAAACTGATGGGGTTATGAGAGCAAAGGTTGGGCTTAGTGGAA
                                                                              

CuAOzeta          TCCTCAGTTTAGGAGCTCTGCAGCCAGGTGAAACTCGAAAG-------------------
CuAObeta          TTTTAGAAGTAAAAGCGACATCGTACACTTCAAACGATCAAATA----------------
CuAOalpha3        TTTTAGAAGTGAAACCGGTAGAATATATTCACACATCCGAAATC---------------A
CuAOalpha1        TTTTAGAAGTTAAACCGGTGAAATATGTTAACACATCCGAGATC----------------
CuAOalpha2        TTTTAGAAGTTAAACCTGTGGAATATGTTCACACATCAGAGATC----------------
CuAOgamma2        TGTTGATGGTGAAAGGAACGGCTTACGAAAACGTTGAAGACTTG---------------G
CuAOgamma1        TGTTAATGGTGAAAGGGACACCTTACGATAATGTAGATGACTTA---------------G
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         TACTAATGGTGAAAGGGACAACATATCAAAACAAAAACCAAGTGGAGAAAGATAAAGACG
CuAOepsilon2      TGTTGATGGTGAAAGGGACAACGTACGAGAACAAGAACCAAGTGAAGAAAGACAAAGAAG
                                                                              

CuAOzeta          -----------------TACGGTACTACTATTGCTCCTGGGTTGTATGCACCAGTCCATC
CuAObeta          -----ACGGAGAACGTATACGGTACACTGGTGGCGAAGAACACTATCGCCGTTAACCACG
CuAOalpha3        AACTAGGGGAAGACATACACGGGACAATTGTCGCCGACAACACCGTCGGTGTTAACCACG
CuAOalpha1        --AAAGAAGACGATATCCATGGGACAATCGTCGCGGACAACACCATTGGAGTTAACCACG
CuAOalpha2        --AAAGAAGACGACATCTACGGGACAATTGTTGCTGACAACACCGTCGGAGTTAACCACG
CuAOgamma2        GTGAGAAAGAGGATGATTCTGGACCGTTGATCTCAGAAAACGTTATAGGAGTCGTCCATG
CuAOgamma1        GTGATAGGGAGGATGATGCTGGACCGTTGATCTCTGAGAATGTGATTGGAGTCGTTCATG
CuAOepsilon1      ----------------------------------------------------TATCC---
CuAOdelta         GTAATGAAGAAGAGCTTCACGGCACGCTTCTGTCTGAAAATGTAATTGGAGTAATACACG
CuAOepsilon2      GTAATGAAGAAGAGCTTTATGGCACGATTCTGTCCGAAAATGTAATTGGAGTTATTCACG
                                                                          *   

CuAOzeta          AACATTTCTTTATCGCTCGCATGGATATGTCTGTTGACTGTAAACCTGCTGAAGCTTTTA
CuAObeta          ACCATTACCTAACGTACTACTTGGACCTCGACGTTGACGGTAACG---GCAATTCCTTGG
CuAOalpha3        ACCATTTCGTGACATTCCGTCTTCATCTTGACATCGACGGTACCG---AAAATTCCTTTG
CuAOalpha1        ACCATTTCGTGACATACCGTCTTGATCTTGACATTGATGGCACGG---ATAATTCTTTTG
CuAOalpha2        ATCACTTCGTGACATTCCGTCTTGATCTTGATATAGATGGTACGG---AAAATTCATTTG
CuAOgamma2        ATCATTTCATATCGTTTCATCTAGACATGGACATTGATGGGTCAGCCAACAACTCCTTCG
CuAOgamma1        ATCATTTCATAACGTTTCATCTAGACATGGATATTGATGGACCGATGAATAATTCTTTGG
CuAOepsilon1      -------------------------------CGTCAACGGT-------------------
CuAOdelta         ATCACTACGTCACTTTTTACCTTGACCTTGACGTCGATGGCCCGG---ACAACTCATTTG
CuAOepsilon2      ACCACTACGTCACTTTTTACCTTGACCTCGATGTCGATGGCCCGG---ACAATTCCTTTG
                                                   *  *  *                    

CuAOzeta          ATCAGGTAGTTGAGGTAAATGTTAGAGTTGACGAGCGAGGTGAGAACAATGTCCACAACA
CuAObeta          TGAAAG----------------CCAAACTCAAAACGGTAAGAGTAACGGAAGTTAACAAA
CuAOalpha3        TTCGTA----------------ACGAACTTGTGACCACGAGGTCTCCAAAATCTGTTAAC
CuAOalpha1        TCCGTA----------------GTGAACTTGTGACCAAGAGGACACCAAAATCTGTTAAC
CuAOalpha2        TTCGTA----------------CCGAACTCGTGACCAAGAGGACTCCAAAATCTGTTAAC
CuAOgamma2        TTAAGG----------------TTCATCTAGAGAAGCAGAGACTTCCAC---CTGGAGAA
CuAOgamma1        TTAAGG----------------TTCATCTAGAGAAGCAGAGAGTTCCAA---CAGGAAAA
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         TTAAAG----------------TGAATCTCAAGAGGCAAGAGACCGAGC---CAGGCGAG
CuAOepsilon2      TTAAAG----------------TGAACCTCAAGAGGCAAGAGACGGCGC---CAGGTGAG
                                                                              

CuAOzeta          ATGCGTTTTATGCGGAAGAGAAGTTACTTAAATCTGAGGCAGTGGCGATGCGTGACTGTG
CuAObeta          ACGTCTTCT---CGGAGGAAGAGTTACTGGACGGTCGTTAAAGAGACGGCGAAAACGGAA
CuAOalpha3        ACACC---------GAGAAAAACCTATTGGACAACGAAGCCAAAGACGGCCAAGACCGAG
CuAOalpha1        ACGCC---------TAGGAAGAGCTATTGGACAAC-------GAAACGGCTGAAAG----
CuAOalpha2        ACACC---------GAGAAAAAGCTATTGGACAACAAAACGAAACACAGCAAAAACCGAG
CuAOgamma2        TCAAG---------GAGAAAGAGTTACTTGAAGGTCAAGAAATATGTAGCCAAGACTGAG
CuAOgamma1        TCGCC---------AAGGAAGAGTTACTTGAAGGTCAAGAAATATATAGCCAAGACTGAG
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         TCACC---------GAGGAAAAGTTACCTAAAAGCTGTTAGGAACATTGCGAAAACCGAA
CuAOepsilon2      TCACC---------TAGGAAAAGTTACATGAAAGCAGTTAGGAACATTGTGAAAACCGAA
                                                                              

CuAOzeta          ACCCTCTTTCTGCTCGCCATTGGATTGTAAGGAACACAAGGACT-------GTAAAC---
CuAObeta          GCTGACGGTAGAGTTCGACTCGGCTCG---GATCCGGTTGAGCTGTTAATAGTAAACCCG
CuAOalpha3        GCAGAGGCTCGGGTGAAACTAGGTTTGAAGG---CGGAGGAGTTAGTTGTGGTTAACCCT
CuAOalpha1        ----------------------------------CAGAGGAGTTGTTGGTGGTTAACCCT
CuAOalpha2        GCAGACGCTCGGGTGAAACTAGGCTTGAGAG---CGGAGGAGTTGGTGGTCGTTAACCCT
CuAOgamma2        AAAGATGCTCAGATCAAGATGAGCCTGTACGACCCCTACGAGTTCCATCTTGTGAACCCT
CuAOgamma1        AAAGATGCTCAGATCAAGTTGAGCCTCTATGACCCATATGAATTCCACATTGTGAACCCG
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         AAGGATGGTCAGATCAAGCTTAGCTTGTACGATCCATCAGAATTCCACGTCATCAACTCT
CuAOepsilon2      AAAGACGGTCAGATCAAGCTTAGCTTGTACGATCCATCAGAATACCACGTCATTAATCCT
                                                                              

CuAOzeta          ------------AGGACGGGCCAATTAACGGGATACAAACTTGTTCCGGGTT------CA
CuAObeta          AACAAGAAGACGAAAATAGGAAATACAGTTGGTTACCGGCTGATACCGGAACATTTACAA
CuAOalpha3        AACCGAAAGACGAAGCATGGCAATGAGGTTGGATACCGTTTACTTCATGGAT---CCGCT
CuAOalpha1        AGTAGGAAAACAAAGCACGGTAATGAGGTTGGATACCGTTTACTTCATGGGCCGGCTTCT
CuAOalpha2        ACCAAAAAAACTAAGCATGGCAATGAGGTTGGATACCGTCTACTTCCTGGGC---CGGCT
CuAOgamma2        AACCGACTTTCTCGGTTAGGGAACCCGGCTGGTTACAAGCTTGTACCTGGTGGTAATGCT
CuAOgamma1        AACCGAAAATCTCGGGTAGGAAACCCGGCTGGTTACAGGATCGTACCGGGTGGTAATGCA
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         GGTAAAACCACTCGGGTCGGAAACCCGACGGGTTATAAGGTCGTTCCTAGAACGACGGCA
CuAOepsilon2      GGTAAAACAACTCGAGTTGGTAACCCGACGGGTTACAAGGTTGTCCCTAGAGCCACAGCA
                                                                              

CuAOzeta          AATTGTTTGCCATTAGCTCGACCCGAGGCGAAGTTTCTAAGA--AGAGCCGCTTTCCTGA
CuAObeta          GCCACTTCGCTTTTAA-----CCGATGATGATTACCCCGAGTTAAGAGCCGGTTACACGA
CuAOalpha3        GCAGGCCCACTCCTGG-----CCCAAGATGATTTCCCGCAGATTCGAGCTGCATTCACCA
CuAOalpha1        GAAGGTCCACTTCTGG-----CTCAAGATGATTACCCACAAATTCGGGCAGCATTTACCA
CuAOalpha2        TCAAGCCCACTTCTTG-----TCCAAGATGACTACCCACAGATTCGGGCAGCATTCACCA
CuAOgamma2        GCAAGTTTGCTC---G-----ATCATGATGATCCACCGCAAATGCGAGGCGCTTTCACAA
CuAOgamma1        GCGAGTTTGCTT---G-----ATCACGATGATCCTCCTCAAATTCGAGGTGCATTCACTA
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         GCTAGTCTACTT---G-----ACCATGATGATCCGCCGCAGAAGAGAGGAGCTTTTACCA
CuAOepsilon2      GCTAGTCTACTT---G-----ACCATGATGATCCACCGCAGAAGAGAGGAGCTTTTACTA
                                                                              

CuAOzeta          AGCATAATCTCTGGGTTACCCGTTACGCCCCAGACGAGAAGTTTCCTGGAGGAGAATTCC
CuAObeta          AATATCCGGTTTGGGTGACCGCCTATGACCGGTCCGAGAGATGGGCCGGTGGGTTTTATA
CuAOalpha3        ACTATAACGTGTGGATCACGCCGTATAACAGGTCAGAGGTTTGGGCAGGTGGTTTGTACG
CuAOalpha1        ACTATAATGTGTGGATCACGCCGTACAACAACACGGAGGTTTGGGCCAGCGGTTTGTACG
CuAOalpha2        ACTACAACGTGTGGATCACACCGTATAACAAATCGGAGGTTTGGGCTAGCGGTTTGTACG
CuAOgamma2        ACAATCAGATATGGGTGACTCGGTATAACCGGTCAGAGCAATGGGCTGGAGGGCTTTTGA
CuAOgamma1        ATAATCAGATATGGGTGACTCCATATAACCGGTCAGAACAATATGCCGGAGGAGTTCTAA
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         ACAACCAAATTTGGGTCACTCCGTACAATAAGTCGGAGCAATGGGCTGGTGGCTTGTTCA
CuAOepsilon2      ATAACCAAATTTGGGTTACTCCCTACAATAAGTCCGAGCAATGGGCTAGTGGTTTATTCA
                                                                              

CuAOzeta          CAAACCAAAACCCACGGGCTGGTGAAGGTCTTGCCACATGGGTGAAACAGAATCGCTCCT
CuAObeta          GTGATCGGAGC---CGTGGCGATGACGGTTTAGCTGTATGGAGTAGTAGGAACAGAGAGA
CuAOalpha3        CTGACAGGAGC---CAAGGCGACGATACGTTGGCAGTGTGGTCTCAAAGGAATAGAAAAA
CuAOalpha1        CTGACCGGAGC---CAAGGCGACGACACGTTAGCCGTTTGGTCCCAAAGGAATAGGAAAA
CuAOalpha2        CTGATCGGAGC---CAAGGTGACGACACATTAGCCGTATGGTCCCAAAGAGATAGGGAAA
CuAOgamma2        TGTACCAGAGC---CGTGGTGAAGACACACTACAAGTTTGGTCCGACAGAGATCGGTCCA
CuAOgamma1        TTTACCAGAGC---CAAGGTGATGACACACTACAAGTTTGGTCAGACCGGGACCGTTCGA
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         CTTACCAAAGC---CATGGTGATGACACTCTTGCAGTTTGGTCAGACAGGGATAGAGACA
CuAOepsilon2      CTTACCAAAGC---CATGGTGATGATACTCTTGCGGTTTGGTCCGACAGAGATAGAGATA
                                                                              

CuAOzeta          TGGAAGAATCTGACGTCGTTCTTTGGTACGTGTTTGGGATCACACATGTTCCTAGACTTG
CuAObeta          TAGAGAACAAAGACATAGTGATGTGGTACAACGTTGGGTTTCATCACATTCCATACCAAG
CuAOalpha3        TAGAGAAGGAAGATATAGTGATGTGGTACACCGTCGGTTTCCACCATGTTCCTAGCCAGG
CuAOalpha1        TAGAGAAGACAGATATAGTGATGTGGTACACTGTCGGATTCCACCATGTCCCTTGCCAGG
CuAOalpha2        TAGAGAACAAAGATATAGTGATGTGGTACACCGTTGGATTCCACCATGTCCCATGCCAAG
CuAOgamma2        TTGAGAACAAGGACATAGTGTTGTGGTATACACTAGGGTTCCATCACGTACCGTGCCAAG
CuAOgamma1        TCGAAAACAAGGACATAGTACTGTGGTACACACTAGGGTTCCATCACGTACCTTGTCAAG
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         TAGAGAACAAGGATATAGTTGTGTGGTATACACTTGGTTTCCATCACATTCCATGTCAAG
CuAOepsilon2      TAGAGAATAAGGACATTGTGGTGTGGTACACGCTTGGGTTCCATCACATTCCATGTCAAG
                                                                              

CuAOzeta          AAGATTGGCCGGTTATGCCCGTCGAACATATTGGTTTCACACTAATGCCACATGGATTTT
CuAObeta          AGGATTTTCCGGTTATGCCAACTCTTCACGGTGGTTTTACTCTTCGGCCTTCAAATTTCT
CuAOalpha3        AAGATTACCCGACGATGCCTACTTTATCCGGTGGCTTTGAGCTCCGACCGACCAACTTTT
CuAOalpha1        AAGATTTTCCGACGATGCCTACTTTGTTTGGTGGCTTTGAACTCCGACCGACCAACTTTT
CuAOalpha2        AAGATTTTCCGACGATGCCTACTATGTTTGGCGGCTTTGAACTTCGGCCAACCAACTTTT
CuAOgamma2        AAGATTTTCCAGTGATGCCAACAATAGCATCTAGCTTTGAACTTAAACCGGTCAATTTCT
CuAOgamma1        AAGATTATCCAGTTATGCCAACCGTTGCGGCTAGCTTTGAACTTAAACCAGCAAATTTCT
CuAOepsilon1      --------------ATGCCGAAC-------------------------------------
CuAOdelta         AAGATTTTCCGATAATGCCCACGGTTTCTTCGAGTTTCGATTTGAAGCCCGTAAACTTTT
CuAOepsilon2      AAGATTTTCCGATAATGCCCACTGTTTCTTCAAGTTTCGATTTGAAGCCCGTAAATTTTT
                                *****                                         

CuAOzeta          TCAACTGCTCACCGGCAGTAGATGTGCCACCGAATCCATGCGAATTGGAGACTAAGGAGA
CuAObeta          TCGATAACGATCCTTTGATTGGG-------------------------------------
CuAOalpha3        TCGAGCGAAACCCTGTCCTCAAGACCAAACCCGTCAA--------------------AGT
CuAOalpha1        TCGAGCAAAATCCTGACCTTAAGACCAAACCCATCAA--------------------ACT
CuAOalpha2        TCGAGCAAAATCCTGTTCTCAAGGCTAAACCTTTCAA--------------------TCT
CuAOgamma2        TCGAATCGAACCCGGTACTTGGGATTTCACCTTTCTT--------------------CGA
CuAOgamma1        TTGAATCCAATCCGATTCTTGGGTCTGCTCCTTTCTT--------------------CGA
CuAOepsilon1      ------------------------------------------------------------
CuAOdelta         TCGAGCGCAATCCAATCCTCAGTGCCGCTCCAAACTT--------------------TGA
CuAOepsilon2      TCGAGCGCAATCCAATCCTTAAGGCCGCTCCAAACTT--------------------TGA
                                                                              

CuAOzeta          GTGAAGTCAAAGAGGTTGTAGCACCGAAAGCTCTTCAGACTGGTTTACTTTCAAAGCTTT
CuAObeta          ---------------------------------------------------TAA------
CuAOalpha3        TACCACCGCTCGAAAGTGCACTCCTAAAAACGA-----------------TTAA------
CuAOalpha1        CAACACCACACCAACGTGCACTGCCAGGAACGA-----------------TTAA------
CuAOalpha2        CACCACCATTCCAAAGTGTACTACGAAGAACGA-----------------ATAA------
CuAOgamma2        GAAAGACTTACCAGTCTGT--------------------------------TAA------
CuAOgamma1        AAAAGACTTACCGGTCTGTAGACC--------------ATTTGCTTCATCTTGA------
CuAOepsilon1      ---------------------------------------------------TGA------
CuAOdelta         ACATGATCTCCCGGTTTGTGGAGTTCAATCTGTTTCTG-----------CTTGA------
CuAOepsilon2      ATATGACCTTCCGGTTTGCGGAGCCAAATCTGATTCTG-----------CTTGA------
                                                                       *      

CuAOzeta          GA
CuAObeta          --
CuAOalpha3        --
CuAOalpha1        --
CuAOalpha2        --
CuAOgamma2        --
CuAOgamma1        --
CuAOepsilon1      --
CuAOdelta         --
CuAOepsilon2      --
                    